### PR TITLE
update withdrawal address

### PR DESCRIPTION
**Pull request by 0xm00k**
Created a function to update the withdrawal address.

### CODE REVIEW

**Comment by kadenzipfel** [comment]
thanks for submitting, sorry for taking so long to get to this. could you please undo the formatting so that the git diff shows only what's being changed?

**Comment by 0xm00k** [comment]
> thanks for submitting, sorry for taking so long to get to this. could you please undo the formatting so that the git diff shows only what's being changed?

Sure made the change.

**Comment by kadenzipfel** [comment]
can you please add tests as well? one test that the owner can update the withdrawal address and one that a non-owner cannot update the withdrawal address

**Comment by 0xm00k** [comment]
Will do 👍🏽

**Pull request closed without merging**
